-- AlterTable
ALTER TABLE "DridexLicense" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "DridexUser" ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0.00,
ADD COLUMN     "location" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "username" SET DEFAULT to_char(now(), 'YYYYMMDDHH24MISS');
